### ISSUE TITLE
Add ANU Cat Labels using Labelify

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/anu-prez-ui-theme#1]
1. Alter [Labelify](https://github.com/Kurrawong/labelify) to allow it to run against a remote RDFLib Store, not just a local graph
2. Create a patch RDF file for missing labels from 
    * use [Semantic Background](https://github.com/Kurrawong/semantic-background)  
    * use [IDN Catalogue](https://data.idnau.org/) of resources for vocab terms
3. Fix broken link in [Labelify on Tools](https://tools.dev.kurrawong.ai/labelify) 
    * GitHub link should go to <https://github.com/Kurrawong/labelify>

This should fix:

* vocab links like <https://vocabularyserver.com/apais/xml.php?skosTema=12>
    * [IDN Themes vocab](https://data.idnau.org/pid/vocab/idn-th)
* Licenses like <https://purl.org/NET/rdflicense/cc-by-nc4.0>
    * either IDN [Data License](https://linked.data.gov.au/def/licenses) vocab or [Sem Background's RDF Licenses](https://github.com/Kurrawong/semantic-background/blob/main/ontologies/rdflicenses.ttl)
* [Data Roles vocab](https://linked.data.gov.au/def/data-roles)
* [Data Access Rights](https://linked.data.gov.au/def/data-access-rights) vocab
    * get from source from PID IRI
* [DCAT](https://www.w3.org/TR/vocab-dcat/) but from Sem Background

**Comment by lalewis1** [comment]
completed.

improved labelify and missing label count down to zero.
