### ISSUE TITLE
Ensure all ANU Agents are in the IDN's AgentsDB

### ISSUE THREAD

**Issue by nicholascar** [Kurrawong/anu-prez-ui-theme#3]
* all ANU departments (https://github.com/idn-au/catalogue-data/issues/49)
* Len Smith - deduplicated (https://github.com/idn-au/idn-metadata-creator/issues/20)
* Gordan Briscoe (he's already in there)

**Comment by lalewis1** [comment]
Just want to be sure that we want the departments included in the IDN catalogue. given that they are of low quality. See [this query](https://anufncatalogue.anu.edu.au/sparql?query=%23%20application%2Fsparql-results%2Bjson%0APREFIX%20sdo%3A%20%3Chttps%3A%2F%2Fschema.org%2F%3E%0Aselect%20distinct%20%3Fdept%20%3Fname%0Awhere%20%7B%0A%20%20%3Fpub%20%3Chttps%3A%2F%2Fanufncatalogue.anu.edu.au%2Fpid%2Fvocab%2Fanufnp%2FhasAuthorAffiliation%3E%20%3Fdept%20.%0A%20%20%3Fdept%20sdo%3Aname%20%3Fname%20.%0A%7D) for the current departments as extracted.

Obviously the extraction could be improved, but I think it would take a lot of manual effort to really clean it up. perhaps a more effective approach would be to get better data from ANU.

**Comment by Metaduck** [comment]
Confirmed that we do want all ANU Indigenous Data Agents supplied in the database. 
Future work will need to be undertaken about access and governance.

**Comment by lalewis1** [comment]
I did as much cleaning as I could to get the data in a more reasonable shape. 

PR Submitted.
